{{- if .Values.networkPolicy.enabled }}
{{- include "dbportal.networkPolicy" (dict "root" . "name" (include "dbportal.fullname" .) "selector" (include "dbportal.selectorLabels" .) "labels" (include "dbportal.labels" .)) }}
{{- end }}
